### ISSUE TITLE
Upgrade dependencies (`analyzer`, etc)

### ISSUE THREAD

**Issue by SleepySquash** [juancastillo0/leto#13]
Thanks for developing such a great package providing GraphQL to the Dart ecosystem!

Currently the `leto_generator` uses `analyzer 4.0.0`, which is quite old and most of the packages nowadays have moved to more recent versions (`5.13.0`, or even `6.0.0`). It'd be nice to upgrade the dependencies, as the `leto_generator` uses some deprecated fields that newer `analyzer` versions remove or refactor.

Personally I stumbled across the dependency lock when tried to use `leto` along with `orm` package: the new versions use the `6.0.0` analyzer.

**Comment by juancastillo0** [comment]
Hi! Thanks for your kind words and sorry for the inconvenience.

I will update the dependencies and release a new version this weekend.

Thanks for the issue!

**Comment by juancastillo0** [comment]
Just published [leto_schema](https://pub.dev/packages/leto_schema) and [leto_generator](https://pub.dev/packages/leto_generator) with updated dependencies in version 0.0.1-dev.4 

Please let me know if there is anything else I can help you with

Thanks again!

**Comment by SleepySquash** [comment]
@juancastillo0, both `leto_schema` and `leto_generator` work like charm, thank you very much for addressing the issue this quickly 🎉
