### ISSUE TITLE
Git clone on the repo fails on windows because filenames contain ':'

### ISSUE THREAD

**Issue by wellers** [juancastillo0/leto#4]
I've been using the repo by adding dependency_overrides in my pubspec.yaml as suggested in this Issue https://github.com/juancastillo0/leto/issues/3. 

My primary OS is Windows 10.

Because they contain a colon, the "Validation: ..." json files located in https://github.com/juancastillo0/leto/tree/main/leto_schema/test/validation/scenarios cause git clone to fail.

This is because a colon is an invalid character for a Windows filename.

**Comment by juancastillo0** [comment]
Hi, thanks for the issue!
I think the last couple of [commits](https://github.com/juancastillo0/leto/commit/ddbbccc58e40b73d84d8c7f9aec19187f4b1fa72) should fix this, I already tested it in a Windows machine.
Please let me know if it isn't working for you or if there is more I can help you with.

**Comment by wellers** [comment]
Hi, thanks for the quick response. 

The updates to those files has now fixed the issue.
